package de.focus_shift.jollyday.tests.country;

import org.junit.jupiter.api.Test;

import java.time.Year;

import static de.focus_shift.jollyday.core.HolidayCalendar.SPAIN;
import static de.focus_shift.jollyday.tests.CalendarCheckerApi.assertFor;
import static java.time.DayOfWeek.MONDAY;
import static java.time.DayOfWeek.SUNDAY;
import static java.time.Month.APRIL;
import static java.time.Month.AUGUST;
import static java.time.Month.DECEMBER;
import static java.time.Month.FEBRUARY;
import static java.time.Month.JANUARY;
import static java.time.Month.JULY;
import static java.time.Month.JUNE;
import static java.time.Month.MARCH;
import static java.time.Month.MAY;
import static java.time.Month.NOVEMBER;
import static java.time.Month.OCTOBER;
import static java.time.Month.SEPTEMBER;

class HolidayESTest {

  @Test
  void ensuresSpanishHolidays() {
    assertFor(SPAIN)
      .hasFixedHoliday("NEW_YEAR", JANUARY, 1)
        .notBetween(Year.of(1900), Year.of(1966))
        .between(Year.of(1967), Year.of(2500))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 6).and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 1).and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 15)
        .canBeShiftedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 12).and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 1).and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 6)
      .notBetween(Year.of(1900), Year.of(1977))
        .between(Year.of(1978), Year.of(2500))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 8).and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .between(Year.of(1900), Year.of(2021))
        .notBetween(Year.of(2022), Year.of(2022))
        .between(Year.of(2023), Year.of(2500))
      .and()
      .hasChristianHoliday("GOOD_FRIDAY").and()

      // Andalusia
      .hasFixedHoliday("REGIONAL", FEBRUARY, 28)
        .inSubdivision("an")
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("an")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("an")
      .notBetween(Year.of(1900), Year.of(2022))
        .between(Year.of(2023), Year.of(2023))
      .notBetween(Year.of(2024), Year.of(2500))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("an")
      .and()

      // Aragon
      .hasFixedHoliday("REGIONAL", APRIL, 23)
        .inSubdivision("ar")
        .canBeShiftedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("ar")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2000), Year.of(2014))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("ar")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("ar")
        .notBetween(Year.of(1900), Year.of(2022))
        .between(Year.of(2023), Year.of(2023))
        .notBetween(Year.of(2024), Year.of(2500))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("ar")
      .and()

      // Principality of Asturias
      .hasFixedHoliday("REGIONAL", SEPTEMBER, 8)
        .inSubdivision("as")
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("as")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("as")
        .notBetween(Year.of(1900), Year.of(2022))
        .between(Year.of(2023), Year.of(2023))
        .notBetween(Year.of(2024), Year.of(2500))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("as")
      .and()

      // Canary Islands
      .hasFixedHoliday("REGIONAL", MAY, 30)
        .inSubdivision("cn")
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("cn")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("cn")
        .between(Year.of(2017), Year.of(2017))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("cn")
      .and()

      // Cantabria
      .hasFixedHoliday("REGIONAL", JULY, 28)
        .inSubdivision("cb")
      .and()
      .hasFixedHoliday("APARECIDA", SEPTEMBER, 15)
        .inSubdivision("cb")
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("cb")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("cb")
      .and()

      // Castile and León
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("cl")
        .between(Year.of(2023), Year.of(2023))
       .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("cl")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2000), Year.of(2014))
      .and()
      .hasFixedHoliday("REGIONAL", APRIL, 23)
        .inSubdivision("cl")
        .between(Year.of(1900), Year.of(2022))
        .notBetween(Year.of(2023), Year.of(2023))
        .between(Year.of(2024), Year.of(2500))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("cl")
        .between(Year.of(2017), Year.of(2017))
        .between(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("cl")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("cl")
      .and()

      // Castile-La Mancha
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("cm")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2000), Year.of(2015))
        .between(Year.of(2020), Year.of(2020))
      .and()
      .hasFixedHoliday("REGIONAL", MAY, 31)
        .inSubdivision("cm")
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("cm")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("CORPUS_CHRISTI").inSubdivision("cm").and()
      .hasChristianHoliday("MAUNDY_THURSDAY").inSubdivision("cm").and()

      // Catalonia
      .hasFixedHoliday("ST_JOHN", JUNE, 24)
        .inSubdivision("ct")
      .and()
      .hasFixedHoliday("REGIONAL", SEPTEMBER, 11)
        .inSubdivision("ct")
      .and()
      .hasFixedHoliday("BOXING_DAY", DECEMBER, 26)
        .inSubdivision("ct")
      .and()
      .hasChristianHoliday("WHIT_MONDAY")
        .inSubdivision("ct")
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .inSubdivision("ct")
      .and()

      // Barcelona
      .hasChristianHoliday("WHIT_MONDAY")
        .inSubdivision("ct", "bcn")
      .and()

      // Ceuta

      // Extremadura
      .hasFixedHoliday("CARNIVAL", FEBRUARY, 2)
        .inSubdivision("ex")
        .between(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("ex")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2000), Year.of(2014))
        .between(Year.of(2017), Year.of(2017))
        .between(Year.of(2021), Year.of(2021))
      .and()
      .hasFixedHoliday("REGIONAL", SEPTEMBER, 8)
        .inSubdivision("ex")
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("ex")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("ex")
      .and()

      // Galicia
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("ga")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2000), Year.of(2014))
        .between(Year.of(2018), Year.of(2021))
      .and()
      .hasFixedHoliday("GALICIAN_LITERATURE", MAY, 17)
        .inSubdivision("ga")
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("ga")
        .between(Year.of(2017), Year.of(2020))
        .between(Year.of(2022), Year.of(2027))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("ga")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("ga")
      .and()

      // Balearic Island
      .hasFixedHoliday("REGIONAL", MARCH, 1)
        .inSubdivision("ib")
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("ib")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .inSubdivision("ib")
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("ib")
      .and()

      // La Rioja
      .hasFixedHoliday("REGIONAL", JUNE, 9)
        .inSubdivision("ri")
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("ri")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .inSubdivision("ri")
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("ri")
      .and()

      // Community of Madrid
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("md")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2000), Year.of(2015))
        .between(Year.of(2017), Year.of(2017))
        .between(Year.of(2021), Year.of(2021))
        .between(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("REGIONAL", MAY, 2)
        .inSubdivision("md")
        .canBeShiftedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("md")
        .between(Year.of(2017), Year.of(2017))
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("md")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY").inSubdivision("md").and()

      // Madrid city
      .hasFixedHoliday("ALMUDENA_DAY" , NOVEMBER, 9)
        .inSubdivision("md", "mad")
      .and()
      .hasFixedHoliday("SAINT_ISIDORE", MAY, 15)
        .inSubdivision("md", "mad")
      .and()

      // Melilla
      .hasIslamicHoliday("ID_UL_ADHA")
        .inSubdivision("ml")
        .between(Year.of(2010), Year.of(2173))
      .and()

      // Region of Murcia
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("mc")
        .between(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("REGIONAL", JUNE, 9)
        .inSubdivision("mc")
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("mc")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("mc")
      .and()

      // Chartered Community of Navarre
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .inSubdivision("nc")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("nc")
        .between(Year.of(2023), Year.of(2023))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("nc")
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .inSubdivision("nc")
      .and()

      // Basque Country
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("pv")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2000), Year.of(2016))
        .between(Year.of(2018), Year.of(2021))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25).inSubdivision("pv")
        .between(Year.of(2017), Year.of(2017))
        .between(Year.of(2019), Year.of(2020))
        .between(Year.of(2022), Year.of(2027))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 25).inSubdivision("pv").between(Year.of(2011), Year.of(2500)).and()
      .hasChristianHoliday("MAUNDY_THURSDAY").inSubdivision("pv").and()
      .hasChristianHoliday("EASTER_MONDAY").inSubdivision("pv").and()

      // Valencia Community
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("vc")
        .canBeShiftedFrom(SUNDAY, MONDAY)
        .between(Year.of(2000), Year.of(2016))
        .between(Year.of(2018), Year.of(2022))
      .and()
      .hasFixedHoliday("REGIONAL", OCTOBER, 9)
        .inSubdivision("vc")
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .inSubdivision("vc")
      .check();
  }
}
