package de.focus_shift.jollyday.tests.country;

import org.junit.jupiter.api.Test;

import java.time.Year;

import static de.focus_shift.jollyday.core.HolidayCalendar.SPAIN;
import static de.focus_shift.jollyday.tests.CalendarCheckerApi.assertFor;
import static java.time.DayOfWeek.MONDAY;
import static java.time.DayOfWeek.SUNDAY;
import static java.time.Month.APRIL;
import static java.time.Month.AUGUST;
import static java.time.Month.DECEMBER;
import static java.time.Month.FEBRUARY;
import static java.time.Month.JANUARY;
import static java.time.Month.JULY;
import static java.time.Month.JUNE;
import static java.time.Month.MARCH;
import static java.time.Month.MAY;
import static java.time.Month.NOVEMBER;
import static java.time.Month.OCTOBER;
import static java.time.Month.SEPTEMBER;

class HolidayESTest {

  @Test
  void ensuresSpanishHolidays() {
    assertFor(SPAIN)
      .hasFixedHoliday("NEW_YEAR", JANUARY, 1)
        .notValidBetween(Year.of(1900), Year.of(1966))
        .validFrom(Year.of(1967))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 6).and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 1).and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 15).and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 12).and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 1).and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 6)
        .notValidBetween(Year.of(1900), Year.of(1977))
        .validFrom(Year.of(1978))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 8).and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        .validTo(Year.of(2021))
        .notValidBetween(Year.of(2022), Year.of(2022))
        .validFrom(Year.of(2023))
      .and()
      .hasChristianHoliday("GOOD_FRIDAY").and()

      // Andalusia
      .hasFixedHoliday("REGIONAL", FEBRUARY, 28)
        .inSubdivision("an")
      .and()
      .hasFixedHoliday("REGIONAL", FEBRUARY, 29)
        .inSubdivision("an")
        .validBetween(Year.of(2016), Year.of(2016))
      .and()
      .hasFixedHoliday("REGIONAL", MARCH, 1)
        .inSubdivision("an")
        .validBetween(Year.of(2021), Year.of(2021))
        .validBetween(Year.of(2027), Year.of(2027))
      .and()
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("an")
        .validBetween(Year.of(1995), Year.of(1995))
        .validBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2012), Year.of(2012))
        .validBetween(Year.of(2017), Year.of(2017))
        .validBetween(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("an")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("an")
        .validBetween(Year.of(1999), Year.of(1999))
        .validBetween(Year.of(2004), Year.of(2004))
        .validBetween(Year.of(2010), Year.of(2010))
        .validBetween(Year.of(2021), Year.of(2021))
        .validBetween(Year.of(2027), Year.of(2027))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 13)
        .inSubdivision("an")
        .validBetween(Year.of(1997), Year.of(1997))
        .validBetween(Year.of(2003), Year.of(2003))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2014), Year.of(2014))
        .validBetween(Year.of(2025), Year.of(2025))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("an")
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("an")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("an")
        .validBetween(Year.of(1996), Year.of(1996))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
        .validBetween(Year.of(2024), Year.of(2024))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("an")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("an")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("an")
      .and()

      // Aragon
      .hasFixedHoliday("REGIONAL", APRIL, 23)
        .inSubdivision("ar")
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("ar")
        .canBeMovedFrom(SUNDAY, MONDAY)
        .validBetween(Year.of(2000), Year.of(2005))
        .notValidBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2007), Year.of(2014))
      .and()
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("ar")
        .validBetween(Year.of(1995), Year.of(1995))
        .validBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2012), Year.of(2012))
        .validBetween(Year.of(2017), Year.of(2017))
        .validBetween(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("ar")
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 20)
        .inSubdivision("ar")
        .validBetween(Year.of(2000), Year.of(2000))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("ar")
        .validBetween(Year.of(1991), Year.of(1992))
        .validBetween(Year.of(1994), Year.of(1995))
        .validBetween(Year.of(2002), Year.of(2002))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("ar")
        .validBetween(Year.of(2010), Year.of(2010))
        .validBetween(Year.of(2021), Year.of(2021))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 13)
        .inSubdivision("ar")
        .validBetween(Year.of(1997), Year.of(1997))
        .validBetween(Year.of(2003), Year.of(2003))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2014), Year.of(2014))
        .validBetween(Year.of(2025), Year.of(2025))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("ar")
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("ar")
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("ar")
        .validBetween(Year.of(1996), Year.of(1996))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
        .validBetween(Year.of(2024), Year.of(2024))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("ar")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("ar")
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("ar")
      .and()

      // Principality of Asturias
      .hasFixedHoliday("REGIONAL", SEPTEMBER, 8)
        .inSubdivision("as")
      .and()
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("as")
        .validBetween(Year.of(1995), Year.of(1995))
        .validBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2012), Year.of(2012))
        .validBetween(Year.of(2017), Year.of(2017))
        .validBetween(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("as")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("as")
        .validBetween(Year.of(1996), Year.of(1996))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("as")
        .validBetween(Year.of(1993), Year.of(1993))
        .validBetween(Year.of(1999), Year.of(1999))
        .validBetween(Year.of(2004), Year.of(2004))
        .validBetween(Year.of(2010), Year.of(2010))
        .validBetween(Year.of(2021), Year.of(2021))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 13)
        .inSubdivision("as")
        .validBetween(Year.of(1997), Year.of(1997))
        .validBetween(Year.of(2003), Year.of(2003))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2014), Year.of(2014))
        .validBetween(Year.of(2025), Year.of(2025))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("as")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("as")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("as")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(1996), Year.of(1996))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
        .validBetween(Year.of(2024), Year.of(2024))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("as")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("as")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("as")
      .and()

      // Canary Islands
      .hasFixedHoliday("REGIONAL", MAY, 30)
        .inSubdivision("cn")
      .and()
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("cn")
        .validBetween(Year.of(1995), Year.of(1995))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("cn")
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("cn")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(1994), Year.of(1998))
        .validBetween(Year.of(2002), Year.of(2003))
        .validBetween(Year.of(2005), Year.of(2005))
        .notValidBetween(Year.of(2017), Year.of(2017))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 26)
        .inSubdivision("cn")
        .validBetween(Year.of(1993), Year.of(1993))
        .validBetween(Year.of(1999), Year.of(1999))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("cn")
        .validBetween(Year.of(1999), Year.of(1999))
        .validBetween(Year.of(2004), Year.of(2004))
        .validBetween(Year.of(2021), Year.of(2021))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("cn")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("cn")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2020), Year.of(2020))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("cn")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(2002), Year.of(2002))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("cn")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("cn")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2016), Year.of(2016))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("cn")
      .and()

      // Cantabria
      .hasFixedHoliday("REGIONAL", JULY, 28)
        .inSubdivision("cb")
      .and()
      .hasFixedHoliday("APARECIDA", SEPTEMBER, 15)
        .inSubdivision("cb")
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("cb")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2013), Year.of(2013))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 20)
        .inSubdivision("cb")
        .validBetween(Year.of(1995), Year.of(1995))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("cb")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(1996), Year.of(1997))
        .validBetween(Year.of(2002), Year.of(2003))
        .validBetween(Year.of(2012), Year.of(2014))
        .validBetween(Year.of(2019), Year.of(2019))
        .validBetween(Year.of(2024), Year.of(2024))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("cb")
        .validBetween(Year.of(2004), Year.of(2004))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 13)
        .inSubdivision("cb")
        .validBetween(Year.of(2008), Year.of(2008))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("cb")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(2015), Year.of(2015))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("cb")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("cb")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("cb")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("cb")
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("cb")
      .and()

      // Castile and León
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("cl")
        .validBetween(Year.of(2017), Year.of(2017))
        .validBetween(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("cl")
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 20)
        .inSubdivision("cl")
        .validBetween(Year.of(1995), Year.of(1995))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("cl")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(1994), Year.of(1995))
        .validBetween(Year.of(1997), Year.of(1997))
        .validBetween(Year.of(2000), Year.of(2000))
        .validBetween(Year.of(2005), Year.of(2006))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2023), Year.of(2023))
        .notValidBetween(Year.of(2017), Year.of(2017))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("cl")
        .validBetween(Year.of(2021), Year.of(2021))
        .validBetween(Year.of(2027), Year.of(2027))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 13)
        .inSubdivision("cl")
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2014), Year.of(2014))
        .validBetween(Year.of(2025), Year.of(2025))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("cl")
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("cl")
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("cl")
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
        .validBetween(Year.of(2024), Year.of(2024))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("cl")
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("cl")
        .canBeMovedFrom(SUNDAY, MONDAY)
        .notValidBetween(Year.of(2000), Year.of(2000))
        .validBetween(Year.of(2001), Year.of(2005))
        .notValidBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2007), Year.of(2014))
      .and()
      .hasFixedHoliday("REGIONAL", APRIL, 23)
        .inSubdivision("cl")
        .validTo(Year.of(2022))
        .notValidBetween(Year.of(2023), Year.of(2023))
        .validFrom(Year.of(2024))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("cl")
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("cl")
      .and()

      // Castile-La Mancha
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("cm")
        .canBeMovedFrom(SUNDAY, MONDAY)
        .notValidBetween(Year.of(2000), Year.of(2000))
        .validBetween(Year.of(2001), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
      .and()
      .hasFixedHoliday("REGIONAL", MAY, 31)
        .inSubdivision("cm")
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("cm")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2013), Year.of(2013))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 20)
        .inSubdivision("cm")
        .validBetween(Year.of(1995), Year.of(1995))
        .validBetween(Year.of(2006), Year.of(2006))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("cm")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("cm")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("cm")
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("cm")
        .validBetween(Year.of(1994), Year.of(1994))
      .and()
      .hasChristianHoliday("CORPUS_CHRISTI").inSubdivision("cm").and()
      .hasChristianHoliday("MAUNDY_THURSDAY").inSubdivision("cm").and()

      // Catalonia
      .hasFixedHoliday("ST_JOHN", JUNE, 24)
        .inSubdivision("ct")
      .and()
      .hasFixedHoliday("REGIONAL", SEPTEMBER, 11)
        .inSubdivision("ct")
      .and()
      .hasFixedHoliday("BOXING_DAY", DECEMBER, 26)
        .inSubdivision("ct")
      .and()
      .hasChristianHoliday("WHIT_MONDAY")
        .inSubdivision("ct")
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .inSubdivision("ct")
      .and()

      // Barcelona
      .hasChristianHoliday("WHIT_MONDAY")
        .inSubdivision("ct", "bcn")
      .and()

      // Ceuta
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("ce")
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
      .and()
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("ce")
        .validBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2012), Year.of(2012))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("ce")
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("ce")
        .validBetween(Year.of(1999), Year.of(1999))
        .validBetween(Year.of(2004), Year.of(2004))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 13)
        .inSubdivision("ce")
        .validBetween(Year.of(1997), Year.of(1997))
        .validBetween(Year.of(2003), Year.of(2003))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2014), Year.of(2014))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("ce")
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("ce")
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("ce")
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2013), Year.of(2013))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("ce")
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
      .and()

      // Extremadura
      .hasFixedHoliday("CARNIVAL_TUESDAY", FEBRUARY, 21)
        .inSubdivision("ex")
        .validBetween(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("ex")
        .canBeMovedFrom(SUNDAY, MONDAY)
        .notValidBetween(Year.of(2000), Year.of(2000))
        .validBetween(Year.of(2001), Year.of(2005))
        .notValidBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2007), Year.of(2014))
        .validBetween(Year.of(2017), Year.of(2017))
        .validBetween(Year.of(2021), Year.of(2021))
      .and()
      .hasFixedHoliday("REGIONAL", SEPTEMBER, 8)
        .inSubdivision("ex")
      .and()
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("ex")
        .validBetween(Year.of(1995), Year.of(1995))
        .validBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2012), Year.of(2012))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("ex")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 20)
        .inSubdivision("ex")
        .validBetween(Year.of(2017), Year.of(2017))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("ex")
        .validBetween(Year.of(1993), Year.of(1993))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 13)
        .inSubdivision("ex")
        .validBetween(Year.of(2003), Year.of(2003))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2014), Year.of(2014))
        .validBetween(Year.of(2025), Year.of(2025))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("ex")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("ex")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("ex")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
        .validBetween(Year.of(2024), Year.of(2024))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("ex")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("ex")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("ex")
      .and()

      // Galicia
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("ga")
        .canBeMovedFrom(SUNDAY, MONDAY)
        .notValidBetween(Year.of(2000), Year.of(2000))
        .validBetween(Year.of(2001), Year.of(2005))
        .notValidBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2007), Year.of(2014))
        .validBetween(Year.of(2018), Year.of(2021))
      .and()
      .hasFixedHoliday("GALICIAN_LITERATURE", MAY, 17)
        .inSubdivision("ga")
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("ga")
        .validBetween(Year.of(1991), Year.of(2027))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("ga")
        .validBetween(Year.of(2015), Year.of(2015))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("ga")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("ga")
      .and()

      // Balearic Island
      .hasFixedHoliday("REGIONAL", MARCH, 1)
        .inSubdivision("ib")
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("ib")
        .validBetween(Year.of(1991), Year.of(1992))
        .validBetween(Year.of(1994), Year.of(1998))
        .validBetween(Year.of(2002), Year.of(2002))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("ib")
        .validBetween(Year.of(1993), Year.of(1993))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 13)
        .inSubdivision("ib")
        .validBetween(Year.of(2008), Year.of(2008))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("ib")
        .validBetween(Year.of(2015), Year.of(2015))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("ib")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("ib")
        .validBetween(Year.of(1991), Year.of(1991))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("ib")
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 27)
        .inSubdivision("ib")
        .validBetween(Year.of(1994), Year.of(1994))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("ib")
        .validBetween(Year.of(2005), Year.of(2005))
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .inSubdivision("ib")
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("ib")
      .and()

      // La Rioja
      .hasFixedHoliday("REGIONAL", JUNE, 9)
        .inSubdivision("ri")
        .validTo(Year.of(2001))
      .and()
      .hasFixedHoliday("REGIONAL", JUNE, 9)
        .inSubdivision("ri")
        .canBeMovedFrom(SUNDAY, MONDAY)
        .validFrom(Year.of(2002))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("ri")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(1996), Year.of(1998))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("ri")
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("ri")
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("ri")
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .inSubdivision("ri")
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("ri")
      .and()

      // Community of Madrid
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("md")
        .canBeMovedFrom(SUNDAY, MONDAY)
        .notValidBetween(Year.of(2000), Year.of(2000))
        .validBetween(Year.of(2001), Year.of(2015))
        .validBetween(Year.of(2017), Year.of(2017))
        .validBetween(Year.of(2021), Year.of(2021))
        .validBetween(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("REGIONAL", MAY, 2)
        .inSubdivision("md")
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("md")
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 20)
        .inSubdivision("md")
        .validBetween(Year.of(1995), Year.of(1995))
        .validBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2017), Year.of(2017))
        .validBetween(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("md")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(1997), Year.of(1997))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
        .validBetween(Year.of(2024), Year.of(2025))
        .notValidBetween(Year.of(2017), Year.of(2017))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("md")
        .validBetween(Year.of(1993), Year.of(1993))
        .validBetween(Year.of(1999), Year.of(1999))
        .validBetween(Year.of(2004), Year.of(2004))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("md")
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("md")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("md")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("md")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY").inSubdivision("md").and()

      // Madrid city
      .hasFixedHoliday("ALMUDENA_DAY" , NOVEMBER, 9)
        .inSubdivision("md", "mad")
      .and()
      .hasFixedHoliday("SAINT_ISIDORE", MAY, 15)
        .inSubdivision("md", "mad")
      .and()

      // Melilla
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("ml")
        .validBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2017), Year.of(2017))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("ml")
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2008), Year.of(2008))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 20)
        .inSubdivision("ml")
        .validBetween(Year.of(2000), Year.of(2000))
        .validBetween(Year.of(2006), Year.of(2006))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("ml")
        .validBetween(Year.of(1999), Year.of(1999))
        .validBetween(Year.of(2004), Year.of(2004))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 13)
        .inSubdivision("ml")
        .validBetween(Year.of(1997), Year.of(1997))
        .validBetween(Year.of(2003), Year.of(2003))
        .validBetween(Year.of(2008), Year.of(2008))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("ml")
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("ml")
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("ml")
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2019), Year.of(2019))
        .validBetween(Year.of(2024), Year.of(2024))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("ml")
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("ml")
        .validBetween(Year.of(2005), Year.of(2005))
      .and()
      .hasIslamicHoliday("ID_UL_ADHA")
        .inSubdivision("ml")
        .validBetween(Year.of(2010), Year.of(2173))
      .and()

      // Region of Murcia
      .hasFixedHoliday("NEW_YEAR", JANUARY, 2)
        .inSubdivision("mc")
        .validBetween(Year.of(2017), Year.of(2017))
        .validBetween(Year.of(2023), Year.of(2023))
      .and()
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("mc")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 20)
        .inSubdivision("mc")
        .validBetween(Year.of(2006), Year.of(2006))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("mc")
        .validBetween(Year.of(1995), Year.of(1995))
      .and()
      .hasFixedHoliday("ASSUMPTION_DAY", AUGUST, 16)
        .inSubdivision("mc")
        .validBetween(Year.of(1993), Year.of(1993))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 13)
        .inSubdivision("mc")
        .validBetween(Year.of(2008), Year.of(2008))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("mc")
        .validBetween(Year.of(1992), Year.of(1992))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("mc")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2009), Year.of(2009))
        .validBetween(Year.of(2015), Year.of(2015))
        .validBetween(Year.of(2020), Year.of(2020))
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("IMMACULATE_CONCEPTION", DECEMBER, 9)
        .inSubdivision("mc")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(1996), Year.of(1996))
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2024), Year.of(2024))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("mc")
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("mc")
        .validBetween(Year.of(2010), Year.of(2016))
        .validBetween(Year.of(2018), Year.of(2021))
        .validBetween(Year.of(2024), Year.of(2027))
      .and()
      .hasFixedHoliday("REGIONAL", JUNE, 9)
        .inSubdivision("mc")
      .and()
      .hasFixedHoliday("REGIONAL", JUNE, 10)
        .inSubdivision("mc")
        .validBetween(Year.of(2002), Year.of(2002))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("mc")
        .validBetween(Year.of(1994), Year.of(1994))
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("mc")
      .and()

      // Chartered Community of Navarre
      .hasFixedHoliday("EPIPHANY", JANUARY, 7)
        .inSubdivision("nc")
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2019), Year.of(2019))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("nc")
        .validBetween(Year.of(1991), Year.of(1992))
        .validBetween(Year.of(1994), Year.of(1995))
        .validBetween(Year.of(1998), Year.of(1998))
        .validBetween(Year.of(2000), Year.of(2000))
        .validBetween(Year.of(2002), Year.of(2003))
        .validBetween(Year.of(2005), Year.of(2006))
        .validBetween(Year.of(2008), Year.of(2009))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2015), Year.of(2017))
        .validBetween(Year.of(2022), Year.of(2025))
      .and()
      .hasFixedHoliday("ALL_SAINTS", NOVEMBER, 2)
        .inSubdivision("nc")
        .validBetween(Year.of(2026), Year.of(2026))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("nc")
        .validBetween(Year.of(1992), Year.of(1992))
        .validBetween(Year.of(2020), Year.of(2020))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("nc")
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2016), Year.of(2016))
        .validBetween(Year.of(2022), Year.of(2022))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY")
        .inSubdivision("nc")
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .inSubdivision("nc")
      .and()

      // Basque Country
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("pv")
        .canBeMovedFrom(SUNDAY, MONDAY)
        .notValidBetween(Year.of(2000), Year.of(2000))
        .validBetween(Year.of(2001), Year.of(2005))
        .notValidBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2007), Year.of(2016))
        .validBetween(Year.of(2018), Year.of(2021))
      .and()
      .hasFixedHoliday("SANTIAGO_APOSTOL", JULY, 25)
        .inSubdivision("pv")
        .validBetween(Year.of(1991), Year.of(1991))
        .validBetween(Year.of(1994), Year.of(1998))
        .validBetween(Year.of(2000), Year.of(2003))
        .validBetween(Year.of(2005), Year.of(2006))
        .validBetween(Year.of(2008), Year.of(2009))
        .validBetween(Year.of(2011), Year.of(2011))
        .validBetween(Year.of(2013), Year.of(2013))
        .validBetween(Year.of(2015), Year.of(2017))
        .validBetween(Year.of(2019), Year.of(2020))
        .validBetween(Year.of(2022), Year.of(2027))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("pv")
        .validBetween(Year.of(1992), Year.of(1992))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 25).inSubdivision("pv").validFrom(Year.of(2011)).and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("pv")
        .validBetween(Year.of(2005), Year.of(2005))
      .and()
      .hasChristianHoliday("MAUNDY_THURSDAY").inSubdivision("pv").and()
      .hasChristianHoliday("EASTER_MONDAY").inSubdivision("pv").and()

      // Valencia Community
      .hasFixedHoliday("ST_JOHN", JUNE, 24)
        .inSubdivision("vc")
      .and()
      .hasFixedHoliday("ST_JOSEPH", MARCH, 19)
        .inSubdivision("vc")
        .canBeMovedFrom(SUNDAY, MONDAY)
        .notValidBetween(Year.of(2000), Year.of(2000))
        .validBetween(Year.of(2001), Year.of(2005))
        .notValidBetween(Year.of(2006), Year.of(2006))
        .validBetween(Year.of(2007), Year.of(2016))
        .validBetween(Year.of(2018), Year.of(2022))
      .and()
      .hasFixedHoliday("REGIONAL", OCTOBER, 9)
        .inSubdivision("vc")
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 2)
        .inSubdivision("vc")
        .validBetween(Year.of(2005), Year.of(2005))
        .validBetween(Year.of(2011), Year.of(2011))
      .and()
      .hasFixedHoliday("CONSTITUTION_DAY", DECEMBER, 7)
        .inSubdivision("vc")
        .validBetween(Year.of(2015), Year.of(2015))
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 26)
        .inSubdivision("vc")
        .validBetween(Year.of(2016), Year.of(2016))
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .inSubdivision("vc")
      .check();
  }
}
