package de.focus_shift.jollyday.tests.country;

import org.junit.jupiter.api.Test;

import java.time.Year;

import static de.focus_shift.jollyday.core.HolidayCalendar.HONG_KONG;
import static de.focus_shift.jollyday.tests.CalendarChecker.Adjuster.PREVIOUS;
import static de.focus_shift.jollyday.tests.CalendarCheckerApi.assertFor;
import static java.time.DayOfWeek.MONDAY;
import static java.time.DayOfWeek.SATURDAY;
import static java.time.DayOfWeek.SUNDAY;
import static java.time.DayOfWeek.TUESDAY;
import static java.time.DayOfWeek.WEDNESDAY;
import static java.time.Month.APRIL;
import static java.time.Month.DECEMBER;
import static java.time.Month.FEBRUARY;
import static java.time.Month.JANUARY;
import static java.time.Month.JULY;
import static java.time.Month.JUNE;
import static java.time.Month.MAY;
import static java.time.Month.OCTOBER;
import static java.time.Month.SEPTEMBER;

class HolidayHKTest {

  @Test
  void ensuresHolidays() {
    assertFor(HONG_KONG)
      .hasFixedHoliday("FIRST_DAY_OF_JANUARY", JANUARY, 1)
        // 1 Jan 2023 is a Sunday, so observed Monday 2 Jan
        .validBetween(Year.of(2023), Year.of(2023))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 18)
        .validBetween(Year.of(2007), Year.of(2007))
        .canBeMovedFrom(SUNDAY, PREVIOUS, SATURDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 19)
        .validBetween(Year.of(2007), Year.of(2007))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 20)
        .validBetween(Year.of(2007), Year.of(2007))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 7)
        .validBetween(Year.of(2008), Year.of(2008))
        .canBeMovedFrom(SUNDAY, PREVIOUS, SATURDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 8)
        .validBetween(Year.of(2008), Year.of(2008))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 9)
        .validBetween(Year.of(2008), Year.of(2008))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", JANUARY, 26)
        .validBetween(Year.of(2009), Year.of(2009))
        .canBeMovedFrom(SUNDAY, PREVIOUS, SATURDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", JANUARY, 27)
        .validBetween(Year.of(2009), Year.of(2009))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", JANUARY, 28)
        .validBetween(Year.of(2009), Year.of(2009))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 14)
        .validBetween(Year.of(2010), Year.of(2010))
        .canBeMovedFrom(SUNDAY, PREVIOUS, SATURDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 15)
        .validBetween(Year.of(2010), Year.of(2010))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 16)
        .validBetween(Year.of(2010), Year.of(2010))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 3)
        .validBetween(Year.of(2011), Year.of(2011))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 4)
        .validBetween(Year.of(2011), Year.of(2011))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 5)
        .validBetween(Year.of(2011), Year.of(2011))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", JANUARY, 23)
        .validBetween(Year.of(2012), Year.of(2012))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", JANUARY, 24)
        .validBetween(Year.of(2012), Year.of(2012))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", JANUARY, 25)
        .validBetween(Year.of(2012), Year.of(2012))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 10)
        .validBetween(Year.of(2013), Year.of(2013))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 11)
        .validBetween(Year.of(2013), Year.of(2013))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 12)
        .validBetween(Year.of(2013), Year.of(2013))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", JANUARY, 31)
        .validBetween(Year.of(2014), Year.of(2014))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 1)
        .validBetween(Year.of(2014), Year.of(2014))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 2)
        .validBetween(Year.of(2014), Year.of(2014))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 19)
        .validBetween(Year.of(2015), Year.of(2015))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 20)
        .validBetween(Year.of(2015), Year.of(2015))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 21)
        .validBetween(Year.of(2015), Year.of(2015))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 8)
        .validBetween(Year.of(2016), Year.of(2016))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 9)
        .validBetween(Year.of(2016), Year.of(2016))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 10)
        .validBetween(Year.of(2016), Year.of(2016))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", JANUARY, 28)
        .validBetween(Year.of(2017), Year.of(2017))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", JANUARY, 29)
        .validBetween(Year.of(2017), Year.of(2017))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", JANUARY, 30)
        .validBetween(Year.of(2017), Year.of(2017))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 16)
        .validBetween(Year.of(2018), Year.of(2018))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 17)
        .validBetween(Year.of(2018), Year.of(2018))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 18)
        .validBetween(Year.of(2018), Year.of(2018))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 5)
        .validBetween(Year.of(2019), Year.of(2019))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 6)
        .validBetween(Year.of(2019), Year.of(2019))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 7)
        .validBetween(Year.of(2019), Year.of(2019))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", JANUARY, 25)
        .validBetween(Year.of(2020), Year.of(2020))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", JANUARY, 26)
        .validBetween(Year.of(2020), Year.of(2020))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", JANUARY, 27)
        .validBetween(Year.of(2020), Year.of(2020))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 12)
        .validBetween(Year.of(2021), Year.of(2021))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 13)
        .validBetween(Year.of(2021), Year.of(2021))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 14)
        .validBetween(Year.of(2021), Year.of(2021))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 1)
        .validBetween(Year.of(2022), Year.of(2022))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 2)
        .validBetween(Year.of(2022), Year.of(2022))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 3)
        .validBetween(Year.of(2022), Year.of(2022))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", JANUARY, 22)
        .validBetween(Year.of(2023), Year.of(2023))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", JANUARY, 23)
        .validBetween(Year.of(2023), Year.of(2023))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", JANUARY, 24)
        .validBetween(Year.of(2023), Year.of(2023))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LUNAR_NEW_YEARS_DAY", FEBRUARY, 10)
        .validBetween(Year.of(2024), Year.of(2024))
        .canBeMovedFrom(SUNDAY, WEDNESDAY)
      .and()
      .hasFixedHoliday("SECOND_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 11)
        .validBetween(Year.of(2024), Year.of(2024))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("THIRD_DAY_OF_LUNAR_NEW_YEAR", FEBRUARY, 12)
        .validBetween(Year.of(2024), Year.of(2024))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 5)
        .validTo(Year.of(2007))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 4)
        .validBetween(Year.of(2008), Year.of(2009))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 6)
        .validBetween(Year.of(2010), Year.of(2010))
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 5)
        .validBetween(Year.of(2011), Year.of(2011))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 4)
        .validBetween(Year.of(2012), Year.of(2013))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 5)
        .validBetween(Year.of(2014), Year.of(2015))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 4)
        .validBetween(Year.of(2016), Year.of(2017))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 5)
        .validBetween(Year.of(2018), Year.of(2019))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 4)
        .validBetween(Year.of(2020), Year.of(2021))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 5)
        .validBetween(Year.of(2022), Year.of(2023))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHING_MING_FESTIVAL", APRIL, 4)
        .validFrom(Year.of(2024))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("LABOUR_DAY", MAY, 1)
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 24)
        .validBetween(Year.of(2007), Year.of(2007))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 12)
        .validBetween(Year.of(2008), Year.of(2008))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 2)
        .validBetween(Year.of(2009), Year.of(2009))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 21)
        .validBetween(Year.of(2010), Year.of(2010))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 10)
        .validBetween(Year.of(2011), Year.of(2011))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", APRIL, 28)
        .validBetween(Year.of(2012), Year.of(2012))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 17)
        .validBetween(Year.of(2013), Year.of(2013))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 6)
        .validBetween(Year.of(2014), Year.of(2014))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 25)
        .validBetween(Year.of(2015), Year.of(2015))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 14)
        .validBetween(Year.of(2016), Year.of(2016))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 3)
        .validBetween(Year.of(2017), Year.of(2017))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 22)
        .validBetween(Year.of(2018), Year.of(2018))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 12)
        .validBetween(Year.of(2019), Year.of(2019))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", APRIL, 30)
        .validBetween(Year.of(2020), Year.of(2020))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 19)
        .validBetween(Year.of(2021), Year.of(2021))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 8)
        .validBetween(Year.of(2022), Year.of(2022))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 26)
        .validBetween(Year.of(2023), Year.of(2023))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("BIRTHDAY_OF_THE_BUDDHA", MAY, 15)
        .validBetween(Year.of(2024), Year.of(2024))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 19)
        .validBetween(Year.of(2007), Year.of(2007))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 8)
        .validBetween(Year.of(2008), Year.of(2008))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", MAY, 28)
        .validBetween(Year.of(2009), Year.of(2009))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 16)
        .validBetween(Year.of(2010), Year.of(2010))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 6)
        .validBetween(Year.of(2011), Year.of(2011))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 23)
        .validBetween(Year.of(2012), Year.of(2012))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 12)
        .validBetween(Year.of(2013), Year.of(2013))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 2)
        .validBetween(Year.of(2014), Year.of(2014))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 20)
        .validBetween(Year.of(2015), Year.of(2015))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 9)
        .validBetween(Year.of(2016), Year.of(2016))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", MAY, 30)
        .validBetween(Year.of(2017), Year.of(2017))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 18)
        .validBetween(Year.of(2018), Year.of(2018))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 7)
        .validBetween(Year.of(2019), Year.of(2019))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 25)
        .validBetween(Year.of(2020), Year.of(2020))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 14)
        .validBetween(Year.of(2021), Year.of(2021))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 3)
        .validBetween(Year.of(2022), Year.of(2022))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 22)
        .validBetween(Year.of(2023), Year.of(2023))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("TUEN_NG_FESTIVAL", JUNE, 10)
        .validBetween(Year.of(2024), Year.of(2024))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("HONG_KONG_SPECIAL_REGION", JULY, 1)
        .validFrom(Year.of(1997))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("70_ANNIVERSARY_VICTORY_CH_VS_JP", SEPTEMBER, 3)
        .validBetween(Year.of(2015), Year.of(2015))
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 26)
        .validBetween(Year.of(2007), Year.of(2007))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 15)
        .validBetween(Year.of(2008), Year.of(2008))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHINESE_MID_AUTUMN_FESTIVAL", OCTOBER, 3)
        .validBetween(Year.of(2009), Year.of(2009))
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 23)
        .validBetween(Year.of(2010), Year.of(2010))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 13)
        .validBetween(Year.of(2011), Year.of(2011))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", OCTOBER, 1)
        .validBetween(Year.of(2012), Year.of(2012))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 20)
        .validBetween(Year.of(2013), Year.of(2013))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 9)
        .validBetween(Year.of(2014), Year.of(2014))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 28)
        .validBetween(Year.of(2015), Year.of(2015))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 16)
        .validBetween(Year.of(2016), Year.of(2016))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", OCTOBER, 5)
        .validBetween(Year.of(2017), Year.of(2017))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 25)
        .validBetween(Year.of(2018), Year.of(2018))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 14)
        .validBetween(Year.of(2019), Year.of(2019))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", OCTOBER, 2)
        .validBetween(Year.of(2020), Year.of(2020))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 22)
        .validBetween(Year.of(2021), Year.of(2021))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 11)
        .validBetween(Year.of(2022), Year.of(2022))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 30)
        .validBetween(Year.of(2023), Year.of(2023))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("DAY_FOLLOWING_CHINESE_MID_AUTUMN", SEPTEMBER, 18)
        .validBetween(Year.of(2024), Year.of(2024))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 19)
        .validBetween(Year.of(2007), Year.of(2007))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 7)
        .validBetween(Year.of(2008), Year.of(2008))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 26)
        .validBetween(Year.of(2009), Year.of(2009))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 16)
        .validBetween(Year.of(2010), Year.of(2010))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 5)
        .validBetween(Year.of(2011), Year.of(2011))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 23)
        .validBetween(Year.of(2012), Year.of(2012))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 13)
        .validBetween(Year.of(2013), Year.of(2013))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 2)
        .validBetween(Year.of(2014), Year.of(2014))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 21)
        .validBetween(Year.of(2015), Year.of(2015))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 9)
        .validBetween(Year.of(2016), Year.of(2016))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 28)
        .validBetween(Year.of(2017), Year.of(2017))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 17)
        .validBetween(Year.of(2018), Year.of(2018))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 7)
        .validBetween(Year.of(2019), Year.of(2019))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 25)
        .validBetween(Year.of(2020), Year.of(2020))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 14)
        .validBetween(Year.of(2021), Year.of(2021))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 4)
        .validBetween(Year.of(2022), Year.of(2022))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 23)
        .validBetween(Year.of(2023), Year.of(2023))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHUNG_YEUNG_FESTIVAL", OCTOBER, 11)
        .validBetween(Year.of(2024), Year.of(2024))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 1)
        .validTo(Year.of(2011))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 2)
        .validBetween(Year.of(2012), Year.of(2012))
      .and()
      .hasFixedHoliday("NATIONAL_DAY", OCTOBER, 1)
        .validFrom(Year.of(2013))
        // 1 Oct 2022 is a Saturday, so observed unmoved
        .validBetween(Year.of(2022), Year.of(2022))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasFixedHoliday("CHRISTMAS", DECEMBER, 25)
        // 25 Dec 2022 is a Sunday, so observed Tuesday 27 Dec (Monday already taken by the day after Christmas)
        .validBetween(Year.of(2022), Year.of(2022))
        .canBeMovedFrom(SUNDAY, TUESDAY)
      .and()
      .hasFixedHoliday("FIRST_WEEKDAY_AFTER_CHRISTMAS", DECEMBER, 26)
        // 26 Dec 2022 is a Monday, so observed unmoved
        .validBetween(Year.of(2022), Year.of(2022))
        .canBeMovedFrom(SUNDAY, MONDAY)
      .and()
      .hasChristianHoliday("GOOD_FRIDAY")
      .and()
      .hasChristianHoliday("DAY_FOLLOWING_GOOD_FRIDAY", true)
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .validTo(Year.of(2014))
      .and()
      .hasChristianHoliday("DAY_FOLLOWING_EASTER_MONDAY", true)
        .validBetween(Year.of(2015), Year.of(2015))
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .validBetween(Year.of(2016), Year.of(2020))
      .and()
      .hasChristianHoliday("DAY_FOLLOWING_EASTER_MONDAY", true)
        .validBetween(Year.of(2021), Year.of(2021))
      .and()
      .hasChristianHoliday("EASTER_MONDAY")
        .validFrom(Year.of(2022))
      .check();
  }
}
