package de.focus_shift.jollyday.pojo.holidays;

import java.time.DayOfWeek;
import java.time.Month;
import java.time.MonthDay;
import java.time.Year;
import java.time.chrono.Chronology;
import java.util.List;

import de.focus_shift.jollyday.core.HolidayType;
import de.focus_shift.jollyday.core.spi.ChristianHolidayType;
import de.focus_shift.jollyday.core.spi.Occurrance;
import de.focus_shift.jollyday.core.spi.Relation;
import de.focus_shift.jollyday.core.spi.With;
import de.focus_shift.jollyday.core.spi.YearCycle;
import de.focus_shift.jollyday.pojo.JavaChristianHoliday;
import de.focus_shift.jollyday.pojo.JavaConfiguration;
import de.focus_shift.jollyday.pojo.JavaFixed;
import de.focus_shift.jollyday.pojo.JavaFixedWeekdayInMonth;
import de.focus_shift.jollyday.pojo.JavaHolidays;
import de.focus_shift.jollyday.pojo.JavaMovingCondition;
import de.focus_shift.jollyday.pojo.JavaRelativeToWeekdayInMonth;

public class Holiday_us {

  public static JavaConfiguration configuration;

  static {
    configuration = new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("NEW_YEAR", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 1)))
      .addFixed(new JavaFixed("MEMORIAL_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1869), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(5, 30)))
      .addFixed(new JavaFixed("JUNETEENTH", HolidayType.OFFICIAL_HOLIDAY, Year.of(2021), null, YearCycle.EVERY_YEAR, List.of(new JavaMovingCondition(DayOfWeek.of(6), With.PREVIOUS, DayOfWeek.of(5)), new JavaMovingCondition(DayOfWeek.of(7), With.NEXT, DayOfWeek.of(1))), MonthDay.of(6, 19)))
      .addFixed(new JavaFixed("INDEPENDENCE_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1776), null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 4)))
      .addFixed(new JavaFixed("VETERANS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1938), null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 11)))
      .addFixed(new JavaFixed("CHRISTMAS", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 25)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("PRESIDENTS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1971), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MEMORIAL_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(5), Occurrance.LAST))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("LABOUR_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1895), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(9), Occurrance.FIRST))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1937), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("THANKSGIVING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1863), null, YearCycle.EVERY_YEAR, DayOfWeek.of(4), Month.of(11), Occurrance.FOURTH))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("ELECTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVEN_YEARS, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(11), Occurrance.FIRST), DayOfWeek.of(2), Relation.AFTER))
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("CONFEDERATE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(4), Occurrance.FOURTH))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("JEFFERSON_DAVIS", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(6), Occurrance.FIRST))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "al", "Alabama"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("ALASKA", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 18)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("SEWARD", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(3), Occurrance.LAST))
      , null, "ak", "Alaska"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "az", "Arizona"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CHRISTMAS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 24)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , null, "ar", "Arkansas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("LINCOLN", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(2, 12)))
      .addFixed(new JavaFixed("CESAR_CHAVEZ", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 31)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 8)))
      .addFixed(new JavaFixed("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 21)))
      , null, "be", "Berkeley")), "ca", "California"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1906), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "co", "Colorado"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("LINCOLN", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(2, 12)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "ct", "Connecticut"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , null, "de", "Delaware"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("CONFEDERATE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(4), Occurrance.FOURTH))
      , null, "fl", "Florida"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("CONFEDERATE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(4), Occurrance.FOURTH))
      , null, "ga", "Georgia"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("KALANIANAOLE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 26)))
      .addFixed(new JavaFixed("KAMEHAMEHA", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 11)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("STATEHOOD", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(5), Month.of(8), Occurrance.THIRD))
      , null, "hi", "Hawaii"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "id", "Idaho"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("LINCOLN", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(2, 12)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("PULASKI", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(3), Occurrance.FIRST))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("ELECTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVEN_YEARS, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(11), Occurrance.FIRST), DayOfWeek.of(2), Relation.AFTER))
      , null, "il", "Illinois"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CHRISTMAS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 24)))
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("ELECTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(5), Occurrance.FIRST), DayOfWeek.of(2), Relation.AFTER))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("ELECTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(11), Occurrance.FIRST), DayOfWeek.of(2), Relation.AFTER))
      , null, "in", "Indiana"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CHRISTMAS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 24)))
      .addFixed(new JavaFixed("NEW_YEARS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 31)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      , null, "ia", "Iowa"), new JavaConfiguration(new JavaHolidays()
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      , null, "ks", "Kansas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CHRISTMAS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 24)))
      .addFixed(new JavaFixed("NEW_YEARS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 31)))
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      , null, "ky", "Kentucky"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addChristianHoliday(new JavaChristianHoliday("christian.MARDI_GRAS", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.MARDI_GRAS, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      , null, "la", "Louisiana"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "me", "Maine"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("SERVICE_REDUCTION", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(5), Occurrance.LAST), DayOfWeek.of(5), Relation.BEFORE))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("ELECTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(11), Occurrance.FIRST), DayOfWeek.of(2), Relation.AFTER))
      , null, "md", "Maryland"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("PATRIOT", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(4), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("EVACUATION", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 17)))
      .addFixed(new JavaFixed("BUNKER_HILL", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 17)))
      , null, "sc", "Suffolk County"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("EVACUATION", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 17)))
      , null, "ca", "Cambridge")), "ma", "Massachusetts"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 30)))
      .addFixed(new JavaFixed("CHRISTMAS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 24)))
      .addFixed(new JavaFixed("NEW_YEARS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 31)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , null, "mi", "Michigan"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , null, "mn", "Minnesota"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("CONFEDERATE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(4), Occurrance.FOURTH))
      , null, "ms", "Mississippi"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("LINCOLN", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(2, 12)))
      .addFixed(new JavaFixed("TRUMAN", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 8)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "mo", "Missouri"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CHRISTMAS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 24)))
      .addFixed(new JavaFixed("NEW_YEARS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 31)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("THANKSGIVING", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(11), Occurrance.FIRST), DayOfWeek.of(2), Relation.AFTER))
      , null, "mt", "Montana"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("ARBOR", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(5), Month.of(4), Occurrance.LAST))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "ne", "Nebraska"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("NEVADA", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(5), Month.of(10), Occurrance.LAST))
      , null, "nv", "Nevada"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , null, "nh", "New Hampshire"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("LINCOLN", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(2, 12)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("ELECTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(11), Occurrance.FIRST), DayOfWeek.of(2), Relation.AFTER))
      , null, "nj", "New Jersey"), new JavaConfiguration(new JavaHolidays()
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "nm", "New Mexico"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixed(new JavaFixed("LINCOLN", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(2, 12)))
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("ELECTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(11), Occurrance.FIRST), DayOfWeek.of(2), Relation.AFTER))
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixedWeekday(new JavaFixedWeekdayInMonth("BROOKLY_QUEENS", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(4), Month.of(6), Occurrance.FIRST))
      , null, "nyc", "New York City")), "ny", "New York"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CHRISTMAS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 24)))
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("CONFEDERATE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(4), Occurrance.FOURTH))
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("INDEPENDENCE_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 20)))
      , null, "ce", "Charlotte"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("INDEPENDENCE_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 20)))
      , null, "me", "Mecklenburg")), "nc", "North Carolina"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , null, "nd", "North Dakota"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "oh", "Ohio"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , null, "ok", "Oklahoma"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , null, "or", "Oregon"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "pa", "Pennsylvania"), new JavaConfiguration(new JavaHolidays()
      .addFixedWeekday(new JavaFixedWeekdayInMonth("VICTORY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(8), Occurrance.SECOND))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "ri", "Rhode Island"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CONFEDERATE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 10)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("ELECTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(11), Occurrance.FIRST), DayOfWeek.of(2), Relation.AFTER))
      , null, "sc", "South Carolina"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "sd", "South Dakota"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CHRISTMAS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 24)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("CONFEDERATE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(4), Occurrance.FOURTH))
      , null, "tn", "Tennesee"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CHRISTMAS_EVE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 24)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("CONFEDERATE", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(4), Occurrance.FOURTH))
      , null, "tx", "Texas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("PIONEER", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 24)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "ut", "Utah"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("BENNINGTON", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(8), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "vt", "Vermont"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("LEE_JACKSON", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD), DayOfWeek.of(5), Relation.BEFORE))
      , null, "va", "Virginia"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , null, "wa", "Washington"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "dc", "District of Columbia"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WEST_VIRGINIA", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 20)))
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      , null, "wv", "West Virginia"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("ELECTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(2), Month.of(9), Occurrance.SECOND))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("COLUMBUS_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1934), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(10), Occurrance.SECOND))
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("ELECTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(11), Occurrance.FIRST), DayOfWeek.of(2), Relation.AFTER))
      , null, "wi", "Wisconsin"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1879), Year.of(1967), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 22)))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("MARTIN_LUTHER_KING", HolidayType.OFFICIAL_HOLIDAY, Year.of(1986), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(1), Occurrance.THIRD))
      .addFixedWeekday(new JavaFixedWeekdayInMonth("WASHINGTONS_BIRTHDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(1968), null, YearCycle.EVERY_YEAR, DayOfWeek.of(1), Month.of(2), Occurrance.THIRD))
      , null, "wy", "Wyoming")), "us", "United States");
  }
}
