package de.focus_shift.jollyday.pojo.holidays;

import java.time.DayOfWeek;
import java.time.Month;
import java.time.MonthDay;
import java.time.chrono.Chronology;
import java.util.List;

import de.focus_shift.jollyday.core.HolidayType;
import de.focus_shift.jollyday.core.spi.ChristianHolidayType;
import de.focus_shift.jollyday.core.spi.Occurrance;
import de.focus_shift.jollyday.core.spi.Relation;
import de.focus_shift.jollyday.core.spi.YearCycle;
import de.focus_shift.jollyday.pojo.JavaChristianHoliday;
import de.focus_shift.jollyday.pojo.JavaConfiguration;
import de.focus_shift.jollyday.pojo.JavaFixed;
import de.focus_shift.jollyday.pojo.JavaFixedWeekdayInMonth;
import de.focus_shift.jollyday.pojo.JavaHolidays;
import de.focus_shift.jollyday.pojo.JavaRelativeToWeekdayInMonth;

public class Holiday_pt {

  public static JavaConfiguration configuration;

  static {
    configuration = new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("NEW_YEAR", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 1)))
      .addFixed(new JavaFixed("LABOUR_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 1)))
      .addFixed(new JavaFixed("FREEDOM_DEMOCRACY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(4, 25)))
      .addFixed(new JavaFixed("NATIONAL_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 10)))
      .addFixed(new JavaFixed("ASSUMPTION_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 15)))
      .addFixed(new JavaFixed("REPUBLIC_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 5)))
      .addFixed(new JavaFixed("ALL_SAINTS", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 1)))
      .addFixed(new JavaFixed("INDEPENDENCE_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 1)))
      .addFixed(new JavaFixed("IMMACULATE_CONCEPTION", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 8)))
      .addFixed(new JavaFixed("CHRISTMAS", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 25)))
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER, Chronology.of("ISO")))
      .addChristianHoliday(new JavaChristianHoliday("christian.CARNIVAL", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.CARNIVAL, Chronology.of("ISO")))
      .addChristianHoliday(new JavaChristianHoliday("christian.GOOD_FRIDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.GOOD_FRIDAY, Chronology.of("ISO")))
      .addChristianHoliday(new JavaChristianHoliday("christian.CORPUS_CHRISTI", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.CORPUS_CHRISTI, Chronology.of("ISO")))
      , List.of(new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.PENTECOST_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.PENTECOST_MONDAY, Chronology.of("ISO")))
      , null, "AGD", "Águeda"), new JavaConfiguration(new JavaHolidays()
      , null, "ALB", "Albergaria-a-Velha"), new JavaConfiguration(new JavaHolidays()
      , null, "AND", "Anadia"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 2)))
      , null, "ARC", "Arouca"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 12)))
      , null, "AVR", "Aveiro"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "CPV", "Castelo de Paiva"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 16)))
      , null, "ESP", "Espinho"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "ETR", "Estarreja"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "ILH", "Ílhavo"), new JavaConfiguration(new JavaHolidays()
      , null, "MLD", "Mealhada"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "MRS", "Murtosa"), new JavaConfiguration(new JavaHolidays()
      , null, "OAZ", "Oliveira de Azeméis"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "VAC", "Vale de Cambra"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.PENTECOST_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.PENTECOST_MONDAY, Chronology.of("ISO")))
      , null, "VGS", "Vagos"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 21)))
      , null, "SVV", "Sever do Vouga"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 11)))
      , null, "SJM", "São João da Madeira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 20)))
      , null, "VFR", "Santa Maria da Feira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 25)))
      , null, "OVR", "Ovar"), new JavaConfiguration(new JavaHolidays()
      , null, "OBR", "Oliveira do Bairro")), "01", "Aveiro"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "VFC", "Vila Franca do Campo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "VPT", "Vila do Porto"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(4, 23)))
      , null, "VLS", "Velas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 16)))
      , null, "SRQ", "São Roque do Pico"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "SCF", "Santa Cruz das Flores"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "SCG", "Santa Cruz da Graciosa"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "RGR", "Ribeira Grande"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 20)))
      , null, "VPV", "Praia da Vitória"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 3)))
      , null, "PVC", "Povoação"), new JavaConfiguration(new JavaHolidays()
      , null, "PDL", "Ponta Delgada"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "NRD", "Nordeste"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 22)))
      , null, "MAD", "Madalena"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "LGP", "Lajes do Pico"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "LGF", "Lajes das Flores"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(4, 11)))
      , null, "LAG", "Lagoa (Açores)"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "HRT", "Horta"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "CRV", "Corvo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 25)))
      , null, "CHT", "Calheta (Açores)"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "AGH", "Angra do Heroísmo")), "20", "Azoren"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      , null, "VDG", "Vidigueira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "SRP", "Serpa"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "ORQ", "Ourique"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "ODM", "Odemira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "MRA", "Moura"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "MTL", "Mértola"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 5)))
      , null, "FAL", "Ferreira do Alentejo"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "CBA", "Cuba"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "CVR", "Castro Verde"), new JavaConfiguration(new JavaHolidays()
      , null, "BJA", "Beja"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 28)))
      , null, "BRC", "Barrancos"), new JavaConfiguration(new JavaHolidays()
      , null, "AVT", "Alvito"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "ADV", "Almodôvar"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "AJT", "Aljustrel")), "02", "Beja"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "AMR", "Amares"), new JavaConfiguration(new JavaHolidays()
      , null, "ANS", "Ansião"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 3)))
      , null, "BCL", "Barcelos"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "BRG", "Braga"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 22)))
      , null, "BGC", "Bragança"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 29)))
      , null, "CBC", "Cabeceiras de Basto"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 13)))
      , null, "CDV", "Cadaval"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "CBT", "Celorico de Basto"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 19)))
      , null, "EPS", "Esposende"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 16)))
      , null, "FAF", "Fafe"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "GMR", "Guimarães"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 19)))
      , null, "PVL", "Póvoa de Lanhoso"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "TBR", "Terras de Bouro"), new JavaConfiguration(new JavaHolidays()
      , null, "VRM", "Vieira do Minho"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "VNF", "Vila Nova de Famalicão"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "VVD", "Vila Verde"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 19)))
      , null, "VIZ", "Vizela")), "03", "Braga"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "AFE", "Alfândega da Fé"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 31)))
      , null, "CRZ", "Carrazeda de Ansiães"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "FEC", "Freixo de Espada à Cinta"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "MCD", "Macedo de Cavaleiros"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 10)))
      , null, "MDR", "Miranda do Douro"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 25)))
      , null, "MDL", "Mirandela"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 15)))
      , null, "MGD", "Mogadouro"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 19)))
      , null, "TMC", "Torre de Moncorvo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 24)))
      , null, "VFL", "Vila Flor"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 10)))
      , null, "VMS", "Vimioso"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 20)))
      , null, "VNH", "Vinhais")), "04", "Bragança"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(4, 26)))
      , null, "BMT", "Belmonte"), new JavaConfiguration(new JavaHolidays()
      , null, "CTB", "Castelo Branco"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 20)))
      , null, "CVL", "Covilhã"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 15)))
      , null, "FND", "Fundão"), new JavaConfiguration(new JavaHolidays()
      , null, "IDN", "Idanha-a-Nova"), new JavaConfiguration(new JavaHolidays()
      , null, "OLR", "Oleiros"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "PNC", "Penamacor"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "PNV", "Proença-a-Nova"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "SRT", "Sertã"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "VLR", "Vila de Rei"), new JavaConfiguration(new JavaHolidays()
      , null, "VVR", "Vila Velha de Ródão")), "05", "Castelo Branco"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 7)))
      , null, "AGN", "Arganil"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 25)))
      , null, "CNT", "Cantanhede"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 4)))
      , null, "CBR", "Coimbra"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 24)))
      , null, "CDN", "Condeixa-a-Nova"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "FIG", "Figueira da Foz"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 13)))
      , null, "GOI", "Góis"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "LSA", "Lousã"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 25)))
      , null, "MIR", "Mira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 1)))
      , null, "MCV", "Miranda do Corvo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "MMV", "Montemor-o-Velho"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 7)))
      , null, "OHP", "Oliveira do Hospital"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(4, 10)))
      , null, "PPS", "Pampilhosa da Serra"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 17)))
      , null, "PCV", "Penacova"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 29)))
      , null, "PNL", "Penela"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 21)))
      , null, "SRE", "Soure"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(4, 10)))
      , null, "TBU", "Tábua"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 13)))
      , null, "PRS", "Vila Nova de Poiares")), "06", "Coimbra"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      , null, "ADL", "Alandroal"), new JavaConfiguration(new JavaHolidays()
      , null, "ARL", "Arraiolos"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "BRB", "Borba"), new JavaConfiguration(new JavaHolidays()
      , null, "ETZ", "Estremoz"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "EVR", "Évora"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 8)))
      , null, "MMN", "Montemor-o-Novo"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "MOR", "Mora"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(2, 2)))
      , null, "MOU", "Mourão"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "PRL", "Portel"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "RDD", "Redondo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "RMZ", "Reguengos de Monsaraz"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 7)))
      , null, "VND", "Vendas Novas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 13)))
      , null, "VNT", "Viana do Alentejo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 16)))
      , null, "VVC", "Vila Viçosa")), "07", "Évora"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 20)))
      , null, "ABF", "Albufeira"), new JavaConfiguration(new JavaHolidays()
      .addRelativeToWeekdayInMonth(new JavaRelativeToWeekdayInMonth("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, new JavaFixedWeekdayInMonth("null", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, DayOfWeek.of(5), Month.of(9), Occurrance.FIRST), DayOfWeek.of(7), Relation.AFTER))
      , null, "ACT", "Alcoutim"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 29)))
      , null, "AJZ", "Aljezur"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "CTM", "Castro Marim"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 7)))
      , null, "FAR", "Faro"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "LGA", "Lagoa"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 27)))
      , null, "LGS", "Lagos"), new JavaConfiguration(new JavaHolidays()
      , null, "LLE", "Loulé"), new JavaConfiguration(new JavaHolidays()
      , null, "MCQ", "Monchique"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "OLH", "Olhão"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 11)))
      , null, "PTM", "Portimão"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 1)))
      , null, "SBA", "São Brás de Alportel"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 3)))
      , null, "SLV", "Silves"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "TVR", "Tavira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 20)))
      , null, "VBP", "Vila do Bispo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 13)))
      , null, "VRS", "Vila Real de Santo António")), "08", "Faro"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "AGB", "Aguiar da Beira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 2)))
      , null, "ALD", "Almeida"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 13)))
      , null, "CLB", "Celorico da Beira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 7)))
      , null, "FCR", "Figueira de Castelo Rodrigo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 29)))
      , null, "FAG", "Fornos de Algodres"), new JavaConfiguration(new JavaHolidays()
      , null, "GVA", "Gouveia"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 27)))
      , null, "GRD", "Guarda"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 4)))
      , null, "MTG", "Manteigas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 11)))
      , null, "MED", "Mêda"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 25)))
      , null, "PNH", "Pinhel"), new JavaConfiguration(new JavaHolidays()
      , null, "SBG", "Sabugal"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 3)))
      , null, "SEI", "Seia"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 29)))
      , null, "TCR", "Trancoso"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 21)))
      , null, "VLF", "Vila Nova de Foz Côa")), "09", "Guarda"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 20)))
      , null, "ACB", "Alcobaça"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "AVZ", "Alvaiázere"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 14)))
      , null, "BTL", "Batalha"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "BBR", "Bombarral"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 15)))
      , null, "CLD", "Caldas da Rainha"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "CPR", "Castanheira de Pera"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "FVN", "Figueiró dos Vinhos"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 22)))
      , null, "LRA", "Leiria"), new JavaConfiguration(new JavaHolidays()
      , null, "MGR", "Marinha Grande"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "NZR", "Nazaré"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 11)))
      , null, "OBD", "Óbidos"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "PGR", "Pedrógão Grande"), new JavaConfiguration(new JavaHolidays()
      , null, "PNI", "Peniche"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 11)))
      , null, "PBL", "Pombal"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "PMS", "Porto de Mós")), "10", "Leiria"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 2)))
      , null, "ALQ", "Alenquer"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 11)))
      , null, "AMD", "Amadora"), new JavaConfiguration(new JavaHolidays()
      , null, "ARV", "Arruda dos Vinhos"), new JavaConfiguration(new JavaHolidays()
      , null, "AZB", "Azambuja"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "CSC", "Cascais"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "LSB", "Lisboa"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 26)))
      , null, "LRS", "Loures"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "LNH", "Lourinhã"), new JavaConfiguration(new JavaHolidays()
      , null, "MFR", "Mafra"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 19)))
      , null, "ODV", "Odivelas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 7)))
      , null, "OER", "Oeiras"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "SNT", "Sintra"), new JavaConfiguration(new JavaHolidays()
      , null, "SMA", "Sobral de Monte Agraço"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "TVD", "Torres Vedras"), new JavaConfiguration(new JavaHolidays()
      , null, "VFX", "Vila Franca de Xira")), "11", "Lissabon"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "CLT", "Calheta"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 16)))
      , null, "CML", "Câmara de Lobos"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 21)))
      , null, "FNC", "Funchal"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 9)))
      , null, "MCH", "Machico"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "PTS", "Ponta do Sol"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 22)))
      , null, "PMZ", "Porto Moniz"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "PST", "Porto Santo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "RBR", "Ribeira Brava"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 15)))
      , null, "SCR", "Santa Cruz"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 25)))
      , null, "STN", "Santana"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 22)))
      , null, "SVC", "São Vicente")), "30", "Madeira"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      , null, "ALT", "Alter do Chão"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "ARR", "Arronches"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "AVS", "Avis"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "CMR", "Campo Maior"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "CVD", "Castelo de Vide"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "CRT", "Crato"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 14)))
      , null, "ELV", "Elvas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(4, 6)))
      , null, "FTR", "Fronteira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 23)))
      , null, "GAV", "Gavião"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "MRV", "Marvão"), new JavaConfiguration(new JavaHolidays()
      , null, "MFT", "Monforte"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "NIS", "Nisa"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "PSR", "Ponte de Sor"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 23)))
      , null, "PTG", "Portalegre"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "SSL", "Sousel")), "12", "Portalegre"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 8)))
      , null, "AMT", "Amarante"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 24)))
      , null, "BAO", "Baião"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "FLG", "Felgueiras"), new JavaConfiguration(new JavaHolidays()
      , null, "GDM", "Gondomar"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "LOU", "Lousada"), new JavaConfiguration(new JavaHolidays()
      , null, "MAI", "Maia"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "MCN", "Marco de Canaveses"), new JavaConfiguration(new JavaHolidays()
      , null, "MTS", "Matosinhos"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 6)))
      , null, "PFR", "Paços de Ferreira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 20)))
      , null, "PRD", "Paredes"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 11)))
      , null, "PNF", "Penafiel"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 1)))
      , null, "PRT", "Porto"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "PVZ", "Póvoa de Varzim"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 11)))
      , null, "STS", "Santo Tirso"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 19)))
      , null, "TRF", "Trofa"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "VLG", "Valongo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "VCD", "Vila do Conde"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "VNG", "Vila Nova de Gaia")), "13", "Porto"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 14)))
      , null, "ABT", "Abrantes"), new JavaConfiguration(new JavaHolidays()
      , null, "ACN", "Alcanena"), new JavaConfiguration(new JavaHolidays()
      , null, "ALR", "Almeirim"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(4, 2)))
      , null, "APC", "Alpiarça"), new JavaConfiguration(new JavaHolidays()
      , null, "BNV", "Benavente"), new JavaConfiguration(new JavaHolidays()
      , null, "CTX", "Cartaxo"), new JavaConfiguration(new JavaHolidays()
      , null, "CHM", "Chamusca"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "CNS", "Constância"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 17)))
      , null, "CCH", "Coruche"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 24)))
      , null, "ENT", "Entroncamento"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "FZZ", "Ferreira do Zêzere"), new JavaConfiguration(new JavaHolidays()
      , null, "GLG", "Golegã"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "MAC", "Mação"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 20)))
      , null, "ORM", "Ourém"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 6)))
      , null, "RMR", "Rio Maior"), new JavaConfiguration(new JavaHolidays()
      , null, "SMG", "Salvaterra de Magos"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 19)))
      , null, "STR", "Santarém"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 22)))
      , null, "SRD", "Sardoal"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 1)))
      , null, "TMR", "Tomar"), new JavaConfiguration(new JavaHolidays()
      , null, "TNV", "Torres Novas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "VNB", "Vila Nova da Barquinha")), "14", "Santarém"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "ASL", "Alcácer do Sal"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "ACH", "Alcochete"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "ALM", "Almada"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 28)))
      , null, "BRR", "Barreiro"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 22)))
      , null, "GDL", "Grândola"), new JavaConfiguration(new JavaHolidays()
      , null, "MTA", "Moita"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "MTJ", "Montijo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 1)))
      , null, "PLM", "Palmela"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 25)))
      , null, "STC", "Santiago do Cacém"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "SXL", "Seixal"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 4)))
      , null, "SSB", "Sesimbra"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 15)))
      , null, "STB", "Setúbal"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 24)))
      , null, "SNS", "Sines")), "15", "Setúbal"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 11)))
      , null, "AVV", "Arcos de Valdevez"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "CMN", "Caminha"), new JavaConfiguration(new JavaHolidays()
      , null, "MLG", "Melgaço"), new JavaConfiguration(new JavaHolidays()
      .addChristianHoliday(new JavaChristianHoliday("christian.EASTER_MONDAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, ChristianHolidayType.EASTER_MONDAY, Chronology.of("ISO")))
      , null, "MNC", "Monção"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 10)))
      , null, "PCR", "Paredes de Coura"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 24)))
      , null, "PTB", "Ponte da Barca"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 20)))
      , null, "PTL", "Ponte de Lima"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(2, 18)))
      , null, "VLC", "Valença"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 20)))
      , null, "VCT", "Viana do Castelo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 1)))
      , null, "VNC", "Vila Nova de Cerveira")), "16", "Viana do Castelo"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 11)))
      , null, "ALJ", "Alijó"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 6)))
      , null, "BTC", "Boticas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(7, 8)))
      , null, "CHV", "Chaves"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 30)))
      , null, "MSF", "Mesão Frio"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 25)))
      , null, "MDB", "Mondim de Basto"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 9)))
      , null, "MTR", "Montalegre"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 8)))
      , null, "MUR", "Murça"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 16)))
      , null, "PRG", "Peso da Régua"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 16)))
      , null, "RPN", "Ribeira de Pena"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "SBS", "Sabrosa"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 13)))
      , null, "SMP", "Santa Marta de Penaguião"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 6)))
      , null, "VPC", "Valpaços"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 22)))
      , null, "VPA", "Vila Pouca de Aguiar"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 13)))
      , null, "VRL", "Vila Real")), "17", "Vila Real"), new JavaConfiguration(new JavaHolidays()
      , List.of(new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "AMM", "Armamar"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "CRS", "Carregal do Sal"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "CDR", "Castro Daire"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "CNF", "Cinfães"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "LMG", "Lamego"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      , null, "MGL", "Mangualde"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "MBR", "Moimenta da Beira"), new JavaConfiguration(new JavaHolidays()
      , null, "MRT", "Mortágua"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "NLS", "Nelas"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(10, 7)))
      , null, "OFR", "Oliveira de Frades"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "PCT", "Penalva do Castelo"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "PND", "Penedono"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 29)))
      , null, "RSD", "Resende"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 3)))
      , null, "SCD", "Santa Comba Dão"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 13)))
      , null, "SJP", "São João da Pesqueira"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 29)))
      , null, "SPS", "São Pedro do Sul"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(8, 20)))
      , null, "SAT", "Sátão"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 3)))
      , null, "SRN", "Sernancelhe"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(6, 24)))
      , null, "TBC", "Tabuaço"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 29)))
      , null, "TRC", "Tarouca"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 16)))
      , null, "TND", "Tondela"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 2)))
      , null, "VNP", "Vila Nova de Paiva"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(9, 21)))
      , null, "VIS", "Viseu"), new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("CITY_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 14)))
      , null, "VZL", "Vouzela")), "18", "Viseu")), "pt", "Portugal");
  }
}
