package de.focus_shift.jollyday.pojo.holidays;

import java.time.MonthDay;
import java.time.Year;

import de.focus_shift.jollyday.core.HolidayType;
import de.focus_shift.jollyday.core.spi.IslamicHolidayType;
import de.focus_shift.jollyday.core.spi.YearCycle;
import de.focus_shift.jollyday.pojo.JavaConfiguration;
import de.focus_shift.jollyday.pojo.JavaFixed;
import de.focus_shift.jollyday.pojo.JavaHolidays;
import de.focus_shift.jollyday.pojo.JavaIslamicHoliday;

public class Holiday_mu {

  public static JavaConfiguration configuration;

  static {
    configuration = new JavaConfiguration(new JavaHolidays()
      .addFixed(new JavaFixed("NEW_YEAR", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 1)))
      .addFixed(new JavaFixed("NEW_YEAR", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(1, 2)))
      .addFixed(new JavaFixed("PUBLIC_HOLIDAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(2023), Year.of(2023), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 3)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2013), Year.of(2013), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 10)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2014), Year.of(2014), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 31)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2015), Year.of(2015), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 19)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2016), Year.of(2016), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 8)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2017), Year.of(2017), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 28)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2018), Year.of(2018), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 16)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2019), Year.of(2019), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 5)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2020), Year.of(2020), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 25)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2021), Year.of(2021), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 12)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2022), Year.of(2022), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 1)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2023), Year.of(2023), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 22)))
      .addFixed(new JavaFixed("CHINESE_SPRING_FESTIVAL", HolidayType.OFFICIAL_HOLIDAY, Year.of(2024), Year.of(2024), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 10)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2013), Year.of(2013), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 27)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2014), Year.of(2014), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 17)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2015), Year.of(2015), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 3)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2016), Year.of(2016), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 24)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2017), Year.of(2017), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 9)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2018), Year.of(2018), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 31)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2019), Year.of(2019), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 21)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2020), Year.of(2020), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 8)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2021), Year.of(2021), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 28)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2022), Year.of(2022), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 18)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2023), Year.of(2023), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 4)))
      .addFixed(new JavaFixed("THAIPOOSAM_CAVEDEE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2024), Year.of(2024), YearCycle.EVERY_YEAR, null, MonthDay.of(1, 25)))
      .addFixed(new JavaFixed("ABOLITION_OF_SLAVERY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(2, 1)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2013), Year.of(2013), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 10)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2014), Year.of(2014), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 27)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2015), Year.of(2015), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 17)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2016), Year.of(2016), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 7)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2017), Year.of(2017), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 24)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2018), Year.of(2018), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 13)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2019), Year.of(2019), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 4)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2020), Year.of(2020), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 21)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2021), Year.of(2021), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 11)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2022), Year.of(2022), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 1)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2023), Year.of(2023), YearCycle.EVERY_YEAR, null, MonthDay.of(2, 18)))
      .addFixed(new JavaFixed("MAHA_SHIVRATREE", HolidayType.OFFICIAL_HOLIDAY, Year.of(2024), Year.of(2024), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 8)))
      .addFixed(new JavaFixed("NATIONAL_DAY", HolidayType.OFFICIAL_HOLIDAY, null, Year.of(2016), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 12)))
      .addFixed(new JavaFixed("INDEPENDENCE_AND_REPUBLIC_DAY", HolidayType.OFFICIAL_HOLIDAY, Year.of(2017), null, YearCycle.EVERY_YEAR, null, MonthDay.of(3, 12)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2013), Year.of(2013), YearCycle.EVERY_YEAR, null, MonthDay.of(4, 11)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2014), Year.of(2014), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 31)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2015), Year.of(2015), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 21)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2016), Year.of(2016), YearCycle.EVERY_YEAR, null, MonthDay.of(4, 8)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2017), Year.of(2017), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 29)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2018), Year.of(2018), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 18)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2019), Year.of(2019), YearCycle.EVERY_YEAR, null, MonthDay.of(4, 6)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2020), Year.of(2020), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 25)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2021), Year.of(2021), YearCycle.EVERY_YEAR, null, MonthDay.of(4, 13)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2022), Year.of(2022), YearCycle.EVERY_YEAR, null, MonthDay.of(4, 2)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2023), Year.of(2023), YearCycle.EVERY_YEAR, null, MonthDay.of(3, 22)))
      .addFixed(new JavaFixed("UGAADI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2024), Year.of(2024), YearCycle.EVERY_YEAR, null, MonthDay.of(4, 9)))
      .addFixed(new JavaFixed("LABOUR_DAY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(5, 1)))
      .addFixed(new JavaFixed("ASSUMPTION_BLESSED_VIRGIN_MARY", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVEN_YEARS, null, MonthDay.of(8, 15)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2013), Year.of(2013), YearCycle.EVERY_YEAR, null, MonthDay.of(9, 10)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2014), Year.of(2014), YearCycle.EVERY_YEAR, null, MonthDay.of(8, 30)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2015), Year.of(2015), YearCycle.EVERY_YEAR, null, MonthDay.of(9, 18)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2016), Year.of(2016), YearCycle.EVERY_YEAR, null, MonthDay.of(9, 6)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2017), Year.of(2017), YearCycle.EVERY_YEAR, null, MonthDay.of(8, 26)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2018), Year.of(2018), YearCycle.EVERY_YEAR, null, MonthDay.of(9, 14)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2019), Year.of(2019), YearCycle.EVERY_YEAR, null, MonthDay.of(9, 3)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2020), Year.of(2020), YearCycle.EVERY_YEAR, null, MonthDay.of(8, 23)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2021), Year.of(2021), YearCycle.EVERY_YEAR, null, MonthDay.of(9, 11)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2022), Year.of(2022), YearCycle.EVERY_YEAR, null, MonthDay.of(9, 1)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2023), Year.of(2023), YearCycle.EVERY_YEAR, null, MonthDay.of(9, 20)))
      .addFixed(new JavaFixed("GANESH_CHATURTHI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2024), Year.of(2024), YearCycle.EVERY_YEAR, null, MonthDay.of(9, 8)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2013), Year.of(2013), YearCycle.EVERY_YEAR, null, MonthDay.of(11, 3)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2014), Year.of(2014), YearCycle.EVERY_YEAR, null, MonthDay.of(10, 23)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2015), Year.of(2015), YearCycle.EVERY_YEAR, null, MonthDay.of(11, 11)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2016), Year.of(2016), YearCycle.EVERY_YEAR, null, MonthDay.of(10, 30)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2017), Year.of(2017), YearCycle.EVERY_YEAR, null, MonthDay.of(10, 19)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2018), Year.of(2018), YearCycle.EVERY_YEAR, null, MonthDay.of(11, 7)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2019), Year.of(2019), YearCycle.EVERY_YEAR, null, MonthDay.of(10, 27)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2020), Year.of(2020), YearCycle.EVERY_YEAR, null, MonthDay.of(11, 14)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2021), Year.of(2021), YearCycle.EVERY_YEAR, null, MonthDay.of(11, 4)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2022), Year.of(2022), YearCycle.EVERY_YEAR, null, MonthDay.of(10, 24)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2023), Year.of(2023), YearCycle.EVERY_YEAR, null, MonthDay.of(11, 12)))
      .addFixed(new JavaFixed("DIVALI", HolidayType.OFFICIAL_HOLIDAY, Year.of(2024), Year.of(2024), YearCycle.EVERY_YEAR, null, MonthDay.of(10, 31)))
      .addFixed(new JavaFixed("ALL_SAINTS", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.ODD_YEARS, null, MonthDay.of(11, 1)))
      .addFixed(new JavaFixed("ARRIVAL_OF_INDENTURED_LABORERS", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(11, 2)))
      .addFixed(new JavaFixed("CHRISTMAS", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.EVERY_YEAR, null, MonthDay.of(12, 25)))
      .addIslamicHoliday(new JavaIslamicHoliday("islamic.ID_AL_FITR", HolidayType.OFFICIAL_HOLIDAY, null, Year.of(2010), YearCycle.FOUR_YEARS, null, IslamicHolidayType.ID_AL_FITR_2))
      .addIslamicHoliday(new JavaIslamicHoliday("islamic.ID_AL_FITR", HolidayType.OFFICIAL_HOLIDAY, null, Year.of(2012), YearCycle.FOUR_YEARS, null, IslamicHolidayType.ID_AL_FITR))
      .addIslamicHoliday(new JavaIslamicHoliday("islamic.ID_AL_FITR", HolidayType.OFFICIAL_HOLIDAY, null, null, YearCycle.ODD_YEARS, null, IslamicHolidayType.ID_AL_FITR_2))
      .addIslamicHoliday(new JavaIslamicHoliday("islamic.ID_AL_FITR", HolidayType.OFFICIAL_HOLIDAY, Year.of(2014), null, YearCycle.FOUR_YEARS, null, IslamicHolidayType.ID_AL_FITR_2))
      .addIslamicHoliday(new JavaIslamicHoliday("islamic.ID_AL_FITR", HolidayType.OFFICIAL_HOLIDAY, Year.of(2016), null, YearCycle.FOUR_YEARS, null, IslamicHolidayType.ID_AL_FITR))
      , null, "mu", "Mauritius");
  }
}
